#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE THE REDIS DATABASE
#=================================================
ynh_script_progression --message="Removing Redis database..." --weight=1

ynh_redis_remove_db "$redis_db"

ynh_remove_nginx_config

ynh_remove_fpm_config

ynh_secure_remove --file="/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
